version: '3'
services:
  app:
    image: golang:1.11.4-stretch
    environment:
      - GOPATH=/app
    volumes:
      - ".:/app"
      - "$HOME/pagekite-setup:/pg"
    working_dir: "/app"
    tty: true
